### ISSUE TITLE
generateCacheKey疑问

### ISSUE THREAD

**Issue by logicbaby** [json-iterator/java#1]
这里是不是需要考虑不同的ClassLoader加载进来的同名不同代码的class呢？或者传来的Type有可能也是动态生成的同名不同代码的东东呢~~~~ ；-)

**Comment by slixurd** [comment]
这个必须考虑的,还有Java的RuntimePermission,不然在这些地方会死的很惨....不过作者没考虑到这些问题吧

**Comment by taowen** [comment]
需要 RuntimePermission 的地方就改成静态代码生成吧，比如android。不同 classloader 和动态生成的类就不考虑了。

**Comment by taowen** [comment]
static codegen has been implemented
