### ISSUE TITLE
JSON转对象的问题

### ISSUE THREAD

**Issue by yyblove** [json-iterator/java#10]
我在这里http://jsoniter.com/index.cn.html 看到是可以直接把JSON数据绑定到对象里的， 但是新的版本里， read 是直接传进一个 class ，而不是一个对象！ 请问，我现在怎么把一个json直接生成一个对象？

**Comment by taowen** [comment]
```
public final <T> T read(Class<T> clazz) throws IOException
```
传入一个class，返回绑定的对象

```
public final <T> T read(T existingObject) throws IOException
```
传入一个对象，直接绑定到这个对象上

**Comment by yyblove** [comment]
我用的是这个： compile 'com.jsoniter:jsoniter:0.9.2'  。只看到 com.jsoniter.JsonIterator 里有一个 
```
    public final <T> T read(Class<T> clazz) throws IOException 
```
没有另外一个，而且，整个Class 还有限制的呀？ 内部类居然不能识别出来？

**Comment by taowen** [comment]
内部类不支持。需要类是static的
