### ISSUE TITLE
annotation should be marked on getter/setter if present

### ISSUE THREAD

**Issue by junlincao** [json-iterator/java#110]
[annotation should be marked on getter/setter if present](https://github.com/json-iterator/java/commit/b5be533253e8bb37bbeac535fa09197b4102de09)
这个提交导致如果设置了getter和setter就不能将JsonProperty设置到类属性字段上了，能不能弄个设置开关，可以不抛出异常。之前从gson转过来的话， 一堆annotation需要改到方法上去。而且放到方法上感觉不直观，特别是还有其它annotation也在属性字段上。

之前我是设置在字段上，然后采用
```
    public void updateClassDescriptor(ClassDescriptor desc) {
        for (Binding binding : desc.allBindings()) {
            if (binding.method != null) {
                binding.toNames = new String[0];
                binding.fromNames = new String[0];
            }
        }
        super.updateClassDescriptor(desc);
    }
```
抹除掉getter和setter方法上的binding，这个提交之后不允许这样干了

**Comment by taowen** [comment]
if @JsonProperty is marked on field, ignore getter/setter

how about this?

**Comment by junlincao** [comment]
this is okay
