### ISSUE TITLE
should throw exception for invalid utf8

### ISSUE THREAD

**Issue by taowen** [json-iterator/java#112]

**Comment by plokhotnyuk** [comment]
Please see proposed readString & readObjectFieldsAsHash implementations which throws `JsonException` in case when invalid UTF-8 bytes or invalid JSON escaped characters was detected:
https://github.com/plokhotnyuk/jsoniter-scala/blob/c4b74e29ca232a760300f26276f9fe4d9a724110/macros/src/main/scala/com/jsoniter/CodecBase.scala#L214-L393

Basic tests for them are here: https://github.com/plokhotnyuk/jsoniter-scala/blob/c4b74e29ca232a760300f26276f9fe4d9a724110/macros/src/test/scala/com/jsoniter/CodecBaseSpec.scala

**Comment by taowen** [comment]
https://github.com/json-iterator/java/commit/b394fdd09264014a4c272fa4b2938b576b3c08a0
