### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by stringhuihui** [json-iterator/java#117]
How can i deserialize a json like :[{"name":apple,"age":18},{.............}]? I just need a methed which can accept a json String like [{},{},{},{}] and return me a List .

OR     What can we do to achieve this goal?

This is my first time to use json-iterator.

I‘m i chinese boy can't say accurate English forget it’

**Comment by taowen** [comment]
try `JsonIterator.deserialize(str, List.class)`, the element will be object of map type.

if you have concrete type for list element, use

`JsonIterator.deserialize(str, new TypeLiteral<List<User>>(){}`
