### ISSUE TITLE
无法解析int为0情况

### ISSUE THREAD

**Issue by junlincao** [json-iterator/java#118]
[#115](https://github.com/json-iterator/java/commit/07d21c2270e863f65e714e4587b5c7812c31d340) 提交导致现在无法解析int为0的情况

```
   static class TmpData{
       int intVal;
   }
TmpData b = JsonIterator.deserialize("{\"intVal\":0}", TmpData.class);
```

报错：leading zero is invalid for int

**Comment by taowen** [comment]
fixed by https://github.com/json-iterator/java/pull/116
