### ISSUE TITLE
@JsonIgnore annotation not working when @JsonCreator present in reflection decoding mode

### ISSUE THREAD

**Issue by cedrilino** [json-iterator/java#130]
As it seems, the _@JsonIgnore_ annotation is ignored if an _@JsonCreator_ annotated constructor is present.
The following test

```java
public class JsonIterTest {

	@BeforeClass
	public static void setUp() {
		JsonIterator.setMode(DecodingMode.REFLECTION_MODE);
	}

	public static class TestObject {
		String field1;
		@JsonIgnore
		ActionListener fieldXXX;

		@JsonCreator
		public TestObject(@JsonProperty("field2") String field) {
			field1 = null;
			fieldXXX = e -> System.out.println("field2 is " + field);
		}

		@Override
		public String toString() {
			return "field1=" + field1 + ", field2=" + fieldXXX;
		}
	}

	@Test
	public void simpleParsingTest() throws IOException {
		JsonIterator iter = JsonIterator.parse("{\"field2\": \"test\"}");
		TestObject t = iter.read(TestObject.class);
		System.out.println(t);
	}
}
```

fails with:

```java
java.lang.IllegalArgumentException: Can not set java.awt.event.ActionListener field de.q2web.db.io.json.RuleConfigTest$TestObject.field2 to java.lang.String

	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	...
```

In addition i observed that:

* If we remove the _@JsonIgnore_ annotation, the following exception is thrown:

```java
com.jsoniter.spi.JsonException: no constructor for: interface java.awt.event.ActionListener
	at com.jsoniter.ReflectionObjectDecoder.init(ReflectionObjectDecoder.java:45)
	...
```

* If the line `ActionListener fieldXXX;` is transformed to `String fieldXXX;` and the line `fieldXXX = e -> System.out.println(field);` is removed, no exception is thrown, however the console output yields `field1=null, field2=test` instead of `field1=null, field2=null`.

 * In dynamic decoding mode (`DecodingMode.DYNAMIC_MODE_AND_MATCH_FIELD_WITH_HASH`) everything works fine.

Edit: forgot to mention that I use `jsoniter:0.9.18` with `javassist:3.20.0-GA` ;)

**Comment by taowen** [comment]
on the road, will look into this soon

**Comment by taowen** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/jsoniter/jsoniter/0.9.19-SNAPSHOT/

will cut a new release soon.

**Comment by cedrilino** [comment]
Works great!
Thanks for the fast fix and also thank you for your great project :)
