### ISSUE TITLE
Static code generation broken by 0.9.18 -> 0.9.19

### ISSUE THREAD

**Issue by nedtwigg** [json-iterator/java#135]
When I updated from `0.9.18` to `0.9.19`, static code generation broke for me.  The code gets generated, and put into package `jsoniter_codegen.cfg9223372036535405691`.  At runtime, it looks in `jsoniter_codegen.cfg9223372036100299902`.

What are the giant magic numbers?

**Comment by taowen** [comment]
it is not, it is hash generated from the config. If config is different between static generation and runtime, the number will be different

**Comment by nedtwigg** [comment]
Hashcode of what config?  I added this to my codegen config:

```java
public class CodegenConfig implements StaticCodegenConfig {
	@Override
	public void setup() {
	}

	@Override
	public TypeLiteral[] whatToCodegen() {
		return new TypeLiteral[]{
                           ...
		};
	}

	@Override
	public int hashCode() {
		return 1;
	}
}
```

But the code is still being generated into one package and attempted-to-be-read from another.  I don't think the hashcode of a `Class` object is stable from run to run, so it would be hard to make the hashcode of a codegen config stable...

**Comment by taowen** [comment]
it is .toString().hashCode()

**Comment by nedtwigg** [comment]
toString() is not stable - it depends on the memory address.  For the codegen class I referenced above, 

```
System.out.println(new CodegenConfig().toString()); -> java2ts.CodegenConfig@1540e19d
System.out.println(new CodegenConfig().toString()); -> java2ts.CodegenConfig@677327b6
```

Although, even if I add a stable `toString()` to CodegenConfig, it doesn't fix the bug, so I'm not sure how to make the `spi.Config` stable...

I don't understand what the objective of the obscure naming is?  Why not just codegen to `jsoniter_codegen`?

**Comment by taowen** [comment]
not toString on your CodegenConfig, but the spi.Config. Which is the underlying config used by stream or iterator

https://github.com/json-iterator/java/blob/master/src/main/java/com/jsoniter/JsonIterator.java#L518

You just need to ensure the JsonIterator.setMode(DecodingMode.Static) is called both in runtime and in static codegen.

**Comment by nedtwigg** [comment]
So I changed my setup:

```java
public class CodegenConfig implements StaticCodegenConfig {
	@Override
	public void setup() {
		JsonIterator.setMode(DecodingMode.STATIC_MODE);
		JsonStream.setMode(EncodingMode.STATIC_MODE);
	}
        ....
}
```

and now it seems to work.  I'm a big fan of content-addressable caching, but it seems an odd-fit for this particular usecase.  Might be a bigger picture that I'm missing.

Thanks for helping me fix my issue :)
