### ISSUE TITLE
JsonIgnore not working for private variables

### ISSUE THREAD

**Issue by adgadre** [json-iterator/java#136]
Hi,

There seems to be some issue when serializing private variables with JsonIgnore annotation. The serialized JSON shows private variable marked with @JsonIgnore. The same code works fine if the variable is public.
Below is the sample code and its output for your reference. I'm using Jsoniter version 0.9.19.
Can you please let me know if I'm doing something wrong?

import java.io.IOException;
import com.jsoniter.annotation.JsonIgnore;
import com.jsoniter.output.JsonStream;

public class TestJsoniterObject {

    public static class TestPrivateVariables {
        @JsonIgnore
        private String field1;

        public String getField1() {
            return field1;
        }
    }	

    public static void test_private_serialize() throws IOException {
		TestPrivateVariables obj = new TestPrivateVariables();
        obj.field1 = "hello";
        System.out.println("Private Variables Serialized : "+JsonStream.serialize(obj));
    }	

    public static class TestPublicVariables {
        @JsonIgnore
        public String field1;
    }	
    
    public static void test_public_serialize() throws IOException {
		TestPublicVariables obj = new TestPublicVariables();
        obj.field1 = "hello";
        System.out.println("Public Variables Serialized : "+JsonStream.serialize(obj));
    }	
	
	public static void main(String[] args) {
		try {
			test_private_serialize();
			test_public_serialize();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}

The output:
-------------------------------
Private Variables Serialized : {"field1":"hello"}
Public Variables Serialized : {}
--------------------------------

**Comment by taowen** [comment]
fixed in 0.9.20
