### ISSUE TITLE
How to read below json

### ISSUE THREAD

**Issue by pradeepkusingh** [json-iterator/java#138]
I am a newbie and trying to use this library, what is the best way to read below json paylod ? I tried to use the Any and it is showing blank value.

{
	"suiteName": "Kafka based automation suite",
	"tests": [{
		"testName": "TC001",
		"testAppUrl": "http://mytestapp.com",
		"testRequest": {
			"accountNumber": "1234567890",
			"activationSource": "12312",
			"performFinancialHealthCheck": "yes"
		}
	}]
}

Any records = JsonIterator.deserialize(gData);

for (Any record : records) {
			
		    Any.EntryIterator entryIterator = record.entries();
			
		    while (entryIterator.next()) {
		    
		        System.out.println(
		                entryIterator.key() + " / " + entryIterator.value());
		    }
		}

**Comment by taowen** [comment]
iterator api is not faster than class  binding. do you have specific need to iterate the records? If the whole json is short as above example, I would suggest use bind api instead: http://jsoniter.com/java-features.html#right-api-for-the-right-job

**Comment by pradeepkusingh** [comment]
Thanks, I want to create a generic jason request/response validator and it should be generic, so avoiding the class binding, this is just a sample payload eventually it will increase.

**Comment by pradeepkusingh** [comment]
How can I use any api to make above json payload parsing and validating against another payload more generic ?

**Comment by taowen** [comment]
you want to be fast, you need to be specific. Generic parsing to map of object, can work, but slow.

**Comment by pradeepsingh1234** [comment]
Thanks..DO we have any sample how to use map, I saw docs but not very clear about using MAP?

**Comment by pradeepsingh1234** [comment]
My requirement is to create a Test automation framework and it should be generic enough to be used by any team. So I can't be very specific it should be generic enough to accommodate all kind of json and should be able to validate the requested fields.

**Comment by taowen** [comment]
Map map = JsonIterator.deserialize(input, Map.class);
