### ISSUE TITLE
Fix jsoniter.com domain issues

### ISSUE THREAD

**Issue by d4nirod** [json-iterator/java#139]
http://jsoniter.com/
https://github.com/json-iterator/java
![screen shot 2018-01-03 at 13 40 00](https://user-images.githubusercontent.com/440496/34520998-ad7f473a-f08b-11e7-8e08-8739c4630c27.png)

![screen shot 2018-01-03 at 13 43 56](https://user-images.githubusercontent.com/440496/34521091-38a5f6ce-f08c-11e7-8777-5133ec1921f0.png)

**Comment by taowen** [comment]
thanks, will take sometime to update the domain name
