### ISSUE TITLE
Accents not taken into acount when deserializing

### ISSUE THREAD

**Issue by OwenCalzadilla** [json-iterator/java#146]
I have come across a problem that involves accents. When deserilizing a text that includes an accent (and i guess its no the only character it fails to transform) it gives back the text broken. Here is an example of what im talking about. 
`
String[] aux1 = JsonIterator.deserialize("[\"MARIA\"]", String[].class);
`
`
 String[] aux2 = JsonIterator.deserialize("[\"MARÍA\"]", String[].class);
`
here is an example with two arrays that contain text, one of them includes an accent and the other one does not.
aux1 gives back an object with the text unharmed. The aux2 in the other hand gives back this [MAŔ].
I wanted to know if this is just my fault from bad ussage of the library or if its a real error, and if theres any solution.

**Comment by taowen** [comment]
```java
        String[] aux2 = JsonIterator.deserialize("[\"MARÍA\"]", String[].class);
        System.out.println(aux2[0]);
```

this works fine. I guess it is about the input is not UTF8. can you check your system encoding? jsoniter only supports UTF8.

**Comment by OwenCalzadilla** [comment]
Fixed the problem! thanks for the quick response.
