### ISSUE TITLE
Issue with stream API parsing String and Number attributes

### ISSUE THREAD

**Issue by maurolemos** [json-iterator/java#148]
There seems to be a problem or am I missing something? Why do I get Invalid after reading the first object attribute?

```
iter = JsonIterator.parse("{'id':'9029000000009120445','idwebsite':138963}".replace('\'', '"'));

System.out.println(iter.whatIsNext());
String field = iter.readObject();
System.out.println(field);
System.out.println(iter.readString());
System.out.println(iter.whatIsNext());
```

> OBJECT
id
9029000000009120445
INVALID

I've also tried with class binding and always get the same error:

`Exception in thread "main" com.jsoniter.spi.JsonException: readString: expect string or null, but 1 `

Number fields can't be parsed like this? Cause if I quote the idwebsite value everything works well ..

**Comment by taowen** [comment]
can not use `whatIsNext` in middle of `readObject`. You can use `whatIsNext`, immediately after `readObject`
