### ISSUE TITLE
Explain how numbers are handled

### ISSUE THREAD

**Issue by taowen** [json-iterator/java#149]
* https://github.com/json-iterator/java/issues/61
* https://github.com/json-iterator/java/issues/60
* https://github.com/json-iterator/java/issues/74
* https://github.com/json-iterator/java/issues/147

**Comment by taowen** [comment]
In short, use `Any` instead of `Object`, to control how numbers decoded. By default, all number will be decoded as `Double`. This is the behavior of jackson/gson as well. I will update jsoniter.com tomorrow on this.

**Comment by tomcashman** [comment]
This is not the behaviour of jackson also. I replaced jackson with jsoniter and that's how I encountered #147

**Comment by taowen** [comment]
@tomcashman you are right, seems like jackson will choose Integer/Long/BigInteger automatically

**Comment by taowen** [comment]
released 0.9.21 and added http://jsoniter.com/java-features.html#about-number
