### ISSUE TITLE
Modularization

### ISSUE THREAD

**Issue by Miha-x64** [json-iterator/java#160]
Hello.
I'm currently working on a library for Android which requires JSON parsing.
My requirements are:
— small methods count (DEX limit);
— small bytecode size (smaller APK and faster verification);
— high parsing speed.

I totally like your parser. I've took your streaming code, removed `<T>` parsing, `Any` type, and some other unused stuff; inlined one-liners.
My result is <50 methods and 10.8 KB DEX :)

I think it makes sense to move streaming to another module/artifact so those who need only streaming may use it without other parser parts.

**Comment by taowen** [comment]
I would like to make this change as well. But I do not have time to work on this at the moment. If you want to contribute, just go ahead.

**Comment by Miha-x64** [comment]
If this will break existing API, will you accept such changes?
For example, I may introduce `streaming.JsonIterator`, `ast.JsonTree`, `databind.JsonBind`, and, probably, `jpath.JsonPath` for #89.

**Comment by taowen** [comment]
We can start a V2 version.

**Comment by Miha-x64** [comment]
Ok.
The main idea is to move the core (streaming parser) into its own module, make it very small (merge some classes, inline methods, etc), and make full-featured parser with Any and binding support depend on the core.
I'd also removed base64 copy-paste and added dependency on https://github.com/koron/MiGBase64.

**Comment by jamespedwards42** [comment]
Any chance of bumping the version to Java 9 along with this change to support jigsaw modularity as well?  I maintain a JDK 10 targeted [fork of jsoniter](https://github.com/comodal/jsoniter) with a module-info.java specified so that I can use this as part of a jlink build.

**Comment by Miha-x64** [comment]
Any way to add module-info without breaking Java 6 compatibility?
I haven't ever written code with source = 9 and target = 1.6 :)

**Comment by jamespedwards42** [comment]
No, I don't think it is possible.  I only mentioned it because this would be new version bump so I was hoping it might be a good opportunity to move forward.  Also, forgot to mention, Java 9 has a supplied [Base64 Encoder](https://docs.oracle.com/javase/9/docs/api/java/util/Base64.html).

**Comment by Miha-x64** [comment]
Sadly, Android requires 1.6 bytecode, and this parser is very helpful there since `org.json`, embedded in Android, totally sucks.

You can just [add module-info into your JAR](https://stackoverflow.com/a/39198938/3050249).
