### ISSUE TITLE
Null fields error with wrapper

### ISSUE THREAD

**Issue by xperiafan13-rom** [json-iterator/java#165]
I use the follow wrapper writewrapper
@JsonUnwrapper
    public void writeBeneficiary(JsonStream stream) throws IOException {
        stream.writeObjectField( "cuentaBeneficiario" );
        stream.writeVal( beneficiary.getAccount() );
        stream.writeMore();
        stream.writeObjectField( "emailBeneficiario" );
        stream.writeVal( beneficiary.getEmail() );
        stream.writeMore();
        stream.writeObjectField( "nombreBeneficiario" );
        stream.writeVal( beneficiary.getName() );
        stream.writeMore();
        stream.writeObjectField( "rfcCurpBeneficiario" );
        stream.writeVal( beneficiary.getRfc() );
        stream.writeMore();
        stream.writeObjectField( "tipoCuentaBeneficiario" );
        stream.writeVal( beneficiary.getType().getValue() );
    }

But in response i have:
{
    "claveRastreo": "sdfs",
    "conceptoPago": "vonceptosample",
    "institucionContraparte": {
        "code": 134,
        "name": "institucion"
    },
    "monto": 125.45,
    "cuentaBeneficiario": "123123214",
    "emailBeneficiario": null,   <----- How to hide this?? 
    "nombreBeneficiario": "MiguelBeneficiario",
    "rfcCurpBeneficiario": null,
    "tipoCuentaBeneficiario": 40
}

when I not use wrapper all is ok using this:

Config cfg = new Config.Builder()
                    .omitDefaultValue(true)
                    .encodingMode(EncodingMode.DYNAMIC_MODE)
                    .build();

JsonStream.serialize(cfg, order)

I use 
if (ObjectUtils.anyNotNull(paymentType, null)) {
            stream.writeObjectField("tipoPago");
            stream.writeVal(paymentType.getValue());
        } 
But this add extra ","  to json

Can you help me?

**Comment by taowen** [comment]
you will need to call stream.writeMore(); only if "," is required. There is no easy way to hide the null.
