### ISSUE TITLE
1.0 should be double

### ISSUE THREAD

**Issue by taowen** [json-iterator/java#167]
need to be consistent with jackson

**Comment by liweys** [comment]
String s = in.nextString();
      if(s.contains(".") || s.contains("E") || s.contains("e")) 
        return Double.valueOf(s);

      try {
        long longValue = Long.valueOf(s);
        if (longValue >= Integer.MIN_VALUE && longValue <= Integer.MAX_VALUE)
          return (int) longValue;
        return longValue;
      }catch (NumberFormatException e){
        //e.g., 9223372036854775808 (Long.MAX_VALUE+1) will be parsed as a double
        //which is less than Long.MAX_VALUE because of precision lost
        return Double.valueOf(s);
      }

**Comment by taowen** [comment]
are you reporting a new bug?

**Comment by liweys** [comment]
no, just FYI
