### ISSUE TITLE
user + instead of  String.format()

### ISSUE THREAD

**Issue by nitincchauhan** [json-iterator/java#17]
Interesting benchmark chart !
Could not resist to look at source :)

The low hanging fruit is to replace calls to String.format() with plain + operator of sting **all over**.
eg https://github.com/json-iterator/java/blob/master/src/main/java/com/jsoniter/CodegenImplObject.java#L123

I think the effort would be worth **measurable** gain at little readability cost :)

**Comment by taowen** [comment]
it does not matter, as the codegen is done once, performance will be the same. I choose String.format, because I find it more readable. Others might disagree
