### ISSUE TITLE
permissive mode

### ISSUE THREAD

**Issue by ramarro123** [json-iterator/java#174]
Hello,

there is a way to enable a "permissive" mode for JsonIterator?
something that allow parsing of malformed json.

i have that scenario

{"A":{"B":{},"C":{}}} --> valid json (parsed with my initial code)
{"A":{"B":{},"C":{},}} --> invalid json, throw exception
{'A':{'B':{},"C":{},}} --> invalid json, throw exception (note " and ' are mixed, not sure if it's any difference)

some clients, expecially legacy stuff htat can't be patched, send out json in that way.
json smart it's able to parse that, so i was wondering if it's possible to make it work as well with json-iterator.

the code that i use to parse the json is:
note: it's a "wrong" code, not able to parse a lot of json, including primitive type arrays, but it's already known :) on my case (example show above) this code should work, and it's able to parse the first example. 

```
    public static Element read(String json) throws Throwable {
        JsonIterator.setMode(DecodingMode.STATIC_MODE);
        JsonIterator iter = JsonIterator.parse(json);
        Element root = new Element(iter.readObject());
        consumeObject(root, iter);
        return root;
    }

    private static void consumeObject(Element current, JsonIterator iter) throws Throwable {
        for (String field = iter.readObject(); field != null; field = iter.readObject()) {
            switch (iter.whatIsNext()) {
                case OBJECT:
                    consumeObject(current.addElement(field), iter);
                    break;
                case STRING:
                    current.addAttribute(field, iter.readString());
                    break;
                case BOOLEAN:
                    current.addAttribute(field, iter.readBoolean());
                    break;
                case NUMBER:
                    current.addAttribute(field, iter.readNumberAsString());
                    break;
                case ARRAY:
                    while (iter.readArray()) {
                        Element array_node = current.addElement(field);
                        consumeObject(array_node, iter);
                    }
                    break;
                default:
                    iter.skip();
                    break;
            }
        }
    }
```

**Comment by taowen** [comment]
there are a lot of json parsers supporting malformed json. adding support of it will have performance penalty. jsoniter choose not to do so.
