### ISSUE TITLE
Test Failures & Errors

### ISSUE THREAD

**Issue by santhakr** [json-iterator/java#18]
I get below failures & errors when doing mvn install:

Results :

Failed tests:   test(com.jsoniter.datetime.TestJdkDatetime): expected:<"19[70-01-01T08:00:00.000+]0800"> but was:<"19[69-12-31T16:00:00.000-]0800">
  test_read_byte(com.jsoniter.TestIO): expected:<49> but was:<0>
  test_unread_byte(com.jsoniter.TestIO): expected:<49> but was:<0>

Tests in error: 
  test_empty_array_as_null(com.jsoniter.TestDemo): readString: expect n or ", head: 1, peek: [, buf: []
  test_read_bytes(com.jsoniter.TestIO): javassist.CannotCompileException: by java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "com/jsoniter/IterImpl"
  test_read_any_in_streaming(com.jsoniter.TestReadAny): IterImplSkip: do not know how to skip: 0, head: 0, peek: , buf: 
  test_utf8(com.jsoniter.TestString): readString: expect n or ", head: 0, peek: , buf: 
  test_unicode_escape(com.jsoniter.TestString): readString: expect n or ", head: 0, peek: , buf: 
  test_string_across_buffer(com.jsoniter.TestString): readString: expect n or ", head: 0, peek: , buf: 
  test_normal_escape(com.jsoniter.TestString): readString: expect n or ", head: 0, peek: , buf: 

Tests run: 158, Failures: 3, Errors: 7, Skipped: 0

**Comment by taowen** [comment]
due to class shadowing, streaming tests and non streaming test can not run in same jvm, you can use this for the time being

https://github.com/json-iterator/java/blob/master/src/test/java/com/jsoniter/AllTests.java

I will fix mvn test later

**Comment by taowen** [comment]
`mvn test` is passing in latest master branch now

**Comment by alex-krash** [comment]
Actually, I still have such error (using master branch code)

**Comment by taowen** [comment]
@alex-krash please provide more info

**Comment by alex-krash** [comment]
@taowen , here is an example of my test, failing:
https://gist.github.com/alex-krash/2c4ab0405caa53d098ca5861b60e7bbe

**Comment by taowen** [comment]
this error is expected. You can not enableStreamingSupport after any api has been invoked. It is a YES/NO question, you enableStreamingSupport at the very beginning.
