### ISSUE TITLE
Spaces not trimmed, leading to exception in toBigDecimal()

### ISSUE THREAD

**Issue by nilskp** [json-iterator/java#187]
If the JSON contains spaces, e.g.
```json
{ "number" : 435.22 }
```
Then the value is wrapped as, in this case, a `DoubleLazyAny`, but with the preceeding space still present. This is not a problem if the value is treated as a `double`, but it fails on `.toBigDecimal()`, because it simply calls `new BigDecimal(toString())`.

Seems to me that spaces generally should be trimmed, so perhaps this is a bug in the parsing. If not, it's a bug in the `.toBigDecimal()` implementation.

**Comment by taowen** [comment]
```java
    public String toString() {
        return new String(data, head, tail - head).trim();
    }
```

space should not be a problem here. Did you actually find a bug?

**Comment by nilskp** [comment]
It should be trivial to write a unit test that will fail given the bug description.

**Comment by nilskp** [comment]
@taowen 
Using the latest release 0.9.22:

```java
String json = "{ \"number\" : 435.22 }";
Any obj = JsonIterator.deserialize(json);
BigDecimal bd = obj.get("number").toBigDecimal();
```

I get this:

```
java.lang.NumberFormatException: Character   is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:512)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:400)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:828)
	at com.jsoniter.any.DoubleLazyAny.toBigDecimal(DoubleLazyAny.java:69)
```

If this is in fact fixed, when can we expect a new release?

**Comment by taowen** [comment]
yes, 0.9.22 does not have the fix. Let me cut a new release
