### ISSUE TITLE
decouple stream and any api

### ISSUE THREAD

**Issue by ekuleshov** [json-iterator/java#25]
It would be really nice to have a decoupled version of stream and any apis, so they could be used in Android app without reflection or dynamic code generation, e.g. to replace Jackson tokenizer-based parser.

**Comment by taowen** [comment]
You can use JsonIterator without any dependency. And jar itself is pretty small. What is the point of separating the codebase?

**Comment by ekuleshov** [comment]
Thank you for consideration.

At very least it will make it much easier to ensure app doesn't have any System.out or reflection called at runtime and also will be easier to use jsoniter with Proguard code obfuscator and minifier for Android, especially when static dependencies being analyzed. 

BTW, the jar size is close to Jackson's jar, but it could be much smaller.

**Comment by taowen** [comment]
the jar size is < 100kb, I do not think it would be any kind of problem.
splitting the codebase will make other users hard to manage dependency. I will try to keep this library minimal. Really do not like the jackson style, a json library should not have more than one artifact.

**Comment by ekuleshov** [comment]
I've got 200k+ jar built from the main branch. You already have dependent artifacts for jsoniter module - javassist and Jackson's annotations jar. Those are transparently managed with Maven or Gradle dependency management, so having "binding" module transiently depend on "stream" won't be any issue. Users who need "binding" will declare "binding" dependency and those who only need "stream" can declare "stream" only in their project pom or gradle files.

**Comment by taowen** [comment]
http://mvnrepository.com/artifact/com.jsoniter/jsoniter/0.9.5

the size is 76kb.  javassist and jackson annotation is optional dependency

```xml
        <dependency>
            <groupId>org.javassist</groupId>
            <artifactId>javassist</artifactId>
            <version>3.21.0-GA</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.8.5</version>
            <optional>true</optional>
        </dependency>
```

**Comment by ekuleshov** [comment]
If you download that jar you will see 200k. Size shown on that web page is not correct.
IMHO, optional dependencies make it even worse. You have to guess which ones to add to your project.

**Comment by taowen** [comment]
ok, you are right. Please make a fork, as you wish. I expect most people will use bind-api or any-api.
