### ISSUE TITLE
eliminate circular dependencies between packages

### ISSUE THREAD

**Issue by ekuleshov** [json-iterator/java#26]
I used evaluation version of http://stan4j.com/ dependency analyzer and found that most jasoniter packages tangled to each other, i.e. multiple circular dependencies. See screenshot below.

It would improve design if module packages wouldn't have circular dependencies. For example see http://classycle.sourceforge.net/design.html

<img width="1195" alt="screen shot 2017-01-11 at 2 00 26 am" src="https://cloud.githubusercontent.com/assets/440954/21838810/49a03876-d7a2-11e6-8d81-287f23597b3c.png">

**Comment by taowen** [comment]
the reason is spi do not want to use interface to reference JsonIterator and JsonStream. If we make JsonIterator/JsonStream interface, it will make spi bottom of the dependency tree. however, that will rely on hotspot to devirtualize the call, otherwise the penality of virtual method call will slow us down. Logically, there are three dependency group. iterator/output/spi

**Comment by ekuleshov** [comment]
But there is more than that, e.g. JsoniterSpi depends on java.lang.reflect.* and logic for different gen modes hardcoded in Codegen.gen() method probably could be moved into extensions, so different modes could use/activate corresponding extensions.

**Comment by taowen** [comment]
I will move StringShortDecoder out, it is the only place depending on CodegenAccess, which is not about codgen, but private api of JsonStream.

**Comment by taowen** [comment]
@ekuleshov I just moved StringIntDecoder and other concrete decoders into com.jsoniter.fuzzy. Spi should only depend on JsonStream and JsonIterator now. We can use interface to decouple the package, but I choose not to do that, unless we can prove all mainstream jvm (including android) can devirtualize method calls reliably.

**Comment by taowen** [comment]
added README on package relationship: https://github.com/json-iterator/java/blob/master/src/main/java/com/jsoniter/README.md
