### ISSUE TITLE
Error in the junit tests during package project in Maven

### ISSUE THREAD

**Issue by AGordeevE** [json-iterator/java#29]
Hi
Could you help me?
I'm trying to package this project to jar file use Maven
mvn -f c:\eclipse\Git\json-iter\ package

but I have a lot of junit Errors like this:

junit.framework.ComparisonFailure: expected:<{"field[1":"hello","field2":[1,2]]}
> but was:<{"field[2":[1,2],"field1":"hello"]}>
        at com.jsoniter.output.TestAny.test_my_class(TestAny.java:142)
		
		
I think that is the same:
{"field[1":"hello","field2":[1,2]]}
{"field[2":[1,2],"field1":"hello"]}

but I don't know how can I build jar file.

**Comment by taowen** [comment]
please use the latest master branch and try again. This is known bug, and has been fixed. I will cut a stable release soon.

**Comment by AGordeevE** [comment]
Thanks!
