### ISSUE TITLE
Missing license on various ported sources

### ISSUE THREAD

**Issue by melezov** [json-iterator/java#30]
dsl-json was released under the BSD license, please mark the ported sources accordingly, e.g.:

https://github.com/ngs-doo/dsl-json/blob/master/library/src/main/java/com/dslplatform/json/JsonReader.java#L268
https://github.com/json-iterator/java/blob/master/src/main/java/com/jsoniter/IterImplString.java#L45

**Comment by taowen** [comment]
license have been added to 
number encoding/decoding
string encoding/decoding
