### ISSUE TITLE
Stream API doesn't work without Javassist dependency 

### ISSUE THREAD

**Issue by ekuleshov** [json-iterator/java#32]
Javassist is listed as an optional dependency, however the following method is failing com.jsoniter.JsonIterator.parse(InputStream in, int bufSize) when Javassist is not available.
This shouldn't be happening for stream-only or static code generation.

**Comment by taowen** [comment]
stream api is considered as "optional". 99% percent of time, byte array input will be the best option.

**Comment by ekuleshov** [comment]
Guess I am at that 1%. I have to process large json files and it is not possible to load them into the byte arrays held in memory. It should be possible to use streaming and writer API without dynamically linking anything or generating any code at runtime.

**Comment by taowen** [comment]
The best option is to make a fork of this library. Delete IterImpl.java and rename IterImplForStreaming.java to IterImpl.java. The idea is to support streaming mode without virtual method call. So Javassist is used to shadow the class in runtime.

**Comment by ekuleshov** [comment]
That is pretty much what I had to do, but it is not maintainable like that. I'd have to stick with Jackson if that would be the only option.

As a thought. Maybe make it other way around. Stream by default and replace virtual call when dynamic codegen is used... or provide JsonIteratorStream hardwired with IterImplForStreaming

**Comment by taowen** [comment]
how about I maintain the fork for you? like lite version. It is just a bash script to copy the files needed over. What features do you need? Encoding or decoding? Iterator only or more?

**Comment by ekuleshov** [comment]
Thank you for a generous offer, but that won't be necessary.
I completed evaluation of Jsoniter. Really like simplicity of the stream API. But I didn't get a significant performance increase over jackson 1.x for my project when parsing large json datasets using stream api. Also jackson is more forgiving when parsing various data types. So I will have to keep my existing implementation.

**Comment by taowen** [comment]
switch case based on string field is slow. that is the biggest bottleneck in all the parsing process.

**Comment by ekuleshov** [comment]
I still see quite a bit of jsoniter code at the top of the list:

![image](https://cloud.githubusercontent.com/assets/440954/22514635/f7bd8194-e86d-11e6-8d54-7eab080edcf7.png)
