### ISSUE TITLE
gradle怎么用static-codegen maven插件生成代码？

### ISSUE THREAD

**Issue by maoxianfly** [json-iterator/java#33]
gradle怎么用static-codegen maven插件生成代码？

**Comment by taowen** [comment]
gradle 可以调用 java 进程吗？java com.jsoniter.StaticCodeGenerator -classpath xxx com.jsoniter.demo.DemoCodegenConfig

其实就是执行了com.jsoniter.StaticCodeGenerator 的main函数，参数是一个字符串com.jsoniter.demo.DemoCodegenConfig

**Comment by maoxianfly** [comment]
@taowen 
明白了，谢谢。
