### ISSUE TITLE
Java 17 support & java-json-benchmark

### ISSUE THREAD

**Issue by fabienrenaud** [json-iterator/java#341]
Hi folks,

Someone submitted a PR to _remove_ json-iter from the java-json-benchmark: https://github.com/fabienrenaud/java-json-benchmark/pull/66 Given it's a top-contender lib, I'd like to keep it in the project. Do you have an ETA on when Java 17 will be supported by jsoniter?

**Comment by taowen** [comment]
you can remove it

**Comment by fabienrenaud** [comment]
Out of curiosity: why are you ok with that? :)
I have myself little bandwidth to update the benchmark, so I don't mind waiting for some time...

**Comment by SentryMan** [comment]
> you can remove it

Are you sure?

**Comment by SentryMan** [comment]
It seems we aren't getting a response. @fabienrenaud How do you want to proceed?

**Comment by fabienrenaud** [comment]
Done. Removed.
