### ISSUE TITLE
Lazy模式下，先对数组进行取值，再对数组进行for循环，解析报错

### ISSUE THREAD

**Issue by lhwci** [json-iterator/java#40]
JSON： {"hasMustache":true,"wives":[{"name":"girl-1","age":18,"sex":0,"hight":0},{"name":"girl-2","age":19,"sex":0,"hight":0}],"name":"xxx","age":30,"sex":1,"hight":180.987655}

//示例代码如下，用的是最新的release版本：
Any obj = JsonIterator.deserialize(json);
 obj.toString("wives", 0, "name");
Any wives = obj.get("wives");
// System.out.println("wives=" + wives); //这一句打印先屏蔽
for (Any wife : wives)
{
      System.out.println(wife.get("name"));
}
//示例代码结束

上面的本来只能循环两次，但是在obj.toString("wives", 0, "name");操作完后，再执行for时，Any值不正确了，就导致解析报错。
奇怪的是，如果把上面的那个被屏蔽掉的打印语句放开让其打印，就解析正常。

**Comment by taowen** [comment]
fixed，是 iterator 实现的bug。
