### ISSUE TITLE
Exception in thread "main" com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: readPositiveInt

### ISSUE THREAD

**Issue by menglong567** [json-iterator/java#41]
import com.jsoniter.JsonIterator;
import com.jsoniter.output.JsonStream;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;

public class JsoniterUtil {
    private static final JsoniterUtil instance = new JsoniterUtil();
    private static final Logger logger =
            LoggerFactory.getLogger(JsoniterUtil.class);

    private JsoniterUtil() {
    }

    public static JsoniterUtil getInstance() {
        return instance;
    }

    public  String fromObject2Json(Object obj){
        return JsonStream.serialize(obj);
    }
    public  Object fromJson2Object(String json,Class clas){
        return JsonIterator.deserialize(json,clas);
    }

    public static void main(String[] args) {   
        String value="{\n" +
                "    \"messageType\": \"EUIWebsocketSubscribeMessageTest\",\n" +
                "\t\"sessionid\":\"01dceacc120a495f9c9c2a2bfc6460a7\",\n" +
                "\t\"clientIdentifier\":\"clientA@12347697797\",\n" +
                "\t\"messageUUID\":\"123\",\n" +
                "    \"topics\": [\n" +
                "     \"redisChatTest_ichat\"\n" +
                "    ]\n" +
                "}";
     logger.warn(JsoniterUtil.getInstance().fromJson2Object(value,EUIWebsocketSubscribeMessageTest.class).toString());
    }
}
class EUIWebsocketSubscribeMessageTest {
    private String messageType = "EUIWebsocketSubscribeMessageTest";
    private List<String> topics = new ArrayList();
    private String sessionid = "";
    private int messageUUID;
    private String clientIdentifier;
    public EUIWebsocketSubscribeMessageTest(){}
    public String getMessageType() {
        return messageType;
    }

    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }

    public List<String> getTopics() {
        return topics;
    }

    public void setTopics(List<String> topics) {
        this.topics = topics;
    }

    public String getSessionid() {
        return sessionid;
    }

    public void setSessionid(String sessionid) {
        this.sessionid = sessionid;
    }

    public int getMessageUUID() {
        return messageUUID;
    }

    public void setMessageUUID(int messageUUID) {
        this.messageUUID = messageUUID;
    }

    public String getClientIdentifier() {
        return clientIdentifier;
    }

    public void setClientIdentifier(String clientIdentifier) {
        this.clientIdentifier = clientIdentifier;
    }
}

will report below error for messageUUID filed
---------------------------------------------------------------------------------------------------------------
Exception in thread "main" com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: readPositiveInt: expect 0~9, head: 161, peek: ageUUID":", buf: {
    "messageType": "EUIWebsocketSubscribeMessage",
	"sessionid":"01dceacc120a495f9c9c2a2bfc6460a7",
	"clientIdentifier":"clientA@12347697797",
	"messageUUID":"123",
    "topics": [
     "redisChatTest_ichat"
    ]
}
	at com.jsoniter.ReflectionObjectDecoder$OnlyField.decode(ReflectionObjectDecoder.java:113)
	at com.jsoniter.JsonIterator.read(JsonIterator.java:336)
	at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:373)
	at com.huawei.it.eui.websocket.com.huawei.it.eui.websocket.util.JsoniterUtil.fromJson2Object(JsoniterUtil.java:32)
	at com.huawei.it.eui.websocket.com.huawei.it.eui.websocket.util.JsoniterUtil.main(JsoniterUtil.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by menglong567** [comment]
I tried to update this messageUUID field from long to int ,the same kind error .

**Comment by taowen** [comment]
the input is a string in the json, you can not bind to  int directly

**Comment by taowen** [comment]
MaybeStringLongDecoder

https://www.sitepoint.com/php-style-json-parsing-in-java-with-jsoniter/#databinding
