### ISSUE TITLE
默认设定下，Byte字段反序列化报异常

### ISSUE THREAD

**Issue by xxxyyylll111** [json-iterator/java#43]
默认设定下，Byte字段反序列化报异常：
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at com.jsoniter.ReflectionObjectDecoder.setToBinding(ReflectionObjectDecoder.java:331)
默认的decoder绑定时，入参是short，而set方法的入参数是byte，就报这个异常了。
代码：
`
import com.jsoniter.JsonIterator;
import com.jsoniter.spi.Decoder;
import com.jsoniter.spi.JsoniterSpi;

import java.io.IOException;
import java.io.Serializable;

public class JsoniterTest {
    public static void main(String[] args){
        String json="{\"test\":1}";
        Example example = JsonIterator.deserialize(json,Example.class);;
    }
    static{
        //针对byte转换，用如下方法可以解决，有更好的方式吗？
        JsoniterSpi.registerTypeDecoder(Byte.class,new Decoder() {
            @Override
            public Object decode(JsonIterator iter) throws IOException {
                return (byte)iter.readShort();
            }
        });
    }
}

class Example implements Serializable{
    public Example(){}
    Byte test;
    public Byte getTest() {
        return test;
    }
    public void setTest(Byte test) {
        this.test = test;
    }
}
`

如代码所示，注册自定义的decoder可以解决，有更好的方式吗

**Comment by taowen** [comment]
就自定义decoder吧，主要是 byte[] 的序列化方式不是很统一。
