### ISSUE TITLE
readStringSlowPath error (invalid unicode char)

### ISSUE THREAD

**Issue by feered** [json-iterator/java#44]
I am getting an invalid unicode error on the following JSON string:
`
{
	"System": {
		"EventRecordID": "545488",
		"EventID": "4688",
		"SystemTime": "2017-04-15T14:38:40.327513600Z",
		"Computer": "SS",
		"Provider": "Microsoft-Windows-Security-Auditing",
		"Guid": "{54849625-5478-4994-A5BA-3E3B03V2C30D}",
		"Keywords": "0x8020000000000000",
		"Correlation": "",
		"ProcessID": "4",
		"ThreadID": "19580",
		"Channel": "Security"
	},
	"Data": {
		"SubjectLogonId": "0x65b953",
		"NewProcessId": "0x132c",
		"NewProcessName": "C:\\Users\\SS\\AppData\\Local\\Logitech® Webcam Software\\Logishrd\\LU2.0\\LULnchr.exe",
		"TokenElevationType": "%%1938",
		"ProcessId": "0x4398",
		"CommandLine": "\"C:\\Users\\SS\\AppData\\Local\\Logitech® Webcam Software\\Logishrd\\LU2.0\\LULnchr.exe\"  /lang:ENU /vercfg:2.0 /verman:2.0 /prod:lws /version:13.51.828 /po:0 /qs:hit=2&hcd1=046d_082d_0011 /cn1:facebook /cv1:13.50.854 /cn2:gallery /cv2:13.50.827 /cn3:getmore /cv3:13.50.825 /cn4:help /cv4:13.50.824 /cn5:help_main /cv5:13.50.828 /cn6:launcher /cv6:13.50.828 /cn7:launcher_main /cv7:13.50.815 /cn8:motdet /cv8:13.50.815 /cn9:picvid /cv9:13.50.815 /cn10:twitter /cv10:13.30.1346 /cn11:webcamcontroller /cv11:13.50.815 /cn12:wlmplugin /cv12:13.30.1201 /cn13:youtube /cv13:13.30.1038",
		"TargetUserSid": "S-1-0-0",
		"TargetUserName": "-",
		"TargetDomainName": "-",
		"TargetLogonId": "0x0",
		"ParentProcessName": "C:\\Program Files (x86)\\Logitech\\LWS\\Webcam Software\\LWS.exe",
		"MandatoryLabel": "S-1-16-8192"
	}
}
`

The JSON is valid and doesn't get hung up on any other JSON libraries. My guess is either it's failing on the escape sequence in "CommandLine" value or it's having trouble handling the trademark symbol.

Cheers.

**Comment by taowen** [comment]
```
public void test_invalid_char() {
        String input = "{ \"System\": { \"EventRecordID\": \"545488\", \"EventID\": \"4688\", \"SystemTime\": \"2017-04-15T14:38:40.327513600Z\", \"Computer\": \"SS\", \"Provider\": \"Microsoft-Windows-Security-Auditing\", \"Guid\": \"{54849625-5478-4994-A5BA-3E3B03V2C30D}\", \"Keywords\": \"0x8020000000000000\", \"Correlation\": \"\", \"ProcessID\": \"4\", \"ThreadID\": \"19580\", \"Channel\": \"Security\" }, \"Data\": { \"SubjectLogonId\": \"0x65b953\", \"NewProcessId\": \"0x132c\", \"NewProcessName\": \"C:\\\\Users\\\\SS\\\\AppData\\\\Local\\\\Logitech® Webcam Software\\\\Logishrd\\\\LU2.0\\\\LULnchr.exe\", \"TokenElevationType\": \"%%1938\", \"ProcessId\": \"0x4398\", \"CommandLine\": \"\\\"C:\\\\Users\\\\SS\\\\AppData\\\\Local\\\\Logitech® Webcam Software\\\\Logishrd\\\\LU2.0\\\\LULnchr.exe\\\" /lang:ENU /vercfg:2.0 /verman:2.0 /prod:lws /version:13.51.828 /po:0 /qs:hit=2&hcd1=046d_082d_0011 /cn1:facebook /cv1:13.50.854 /cn2:gallery /cv2:13.50.827 /cn3:getmore /cv3:13.50.825 /cn4:help /cv4:13.50.824 /cn5:help_main /cv5:13.50.828 /cn6:launcher /cv6:13.50.828 /cn7:launcher_main /cv7:13.50.815 /cn8:motdet /cv8:13.50.815 /cn9:picvid /cv9:13.50.815 /cn10:twitter /cv10:13.30.1346 /cn11:webcamcontroller /cv11:13.50.815 /cn12:wlmplugin /cv12:13.30.1201 /cn13:youtube /cv13:13.30.1038\", \"TargetUserSid\": \"S-1-0-0\", \"TargetUserName\": \"-\", \"TargetDomainName\": \"-\", \"TargetLogonId\": \"0x0\", \"ParentProcessName\": \"C:\\\\Program Files (x86)\\\\Logitech\\\\LWS\\\\Webcam Software\\\\LWS.exe\", \"MandatoryLabel\": \"S-1-16-8192\" } }";
        Any obj = JsonIterator.deserialize(input);
        assertEquals("C:\\Users\\SS\\AppData\\Local\\Logitech® Webcam Software\\Logishrd\\LU2.0\\LULnchr.exe", obj.get("Data", "NewProcessName").toString());
    }
```

can not reproduce, using read any. Can you give me your sample code?

**Comment by feered** [comment]
The data that is coming in is through a stream. I am going to do some more debugging to try and reproduce this issue via a file.

It looks like I am failing on more than one of the fields:

![Debug window](http://i.imgur.com/LPDfPq9.png)

**Comment by taowen** [comment]
Is the stream encoded in UTF-8? Only UTF-8 byte stream is supported

**Comment by feered** [comment]
@taowen Sorry for the delay, I have been on the road. I will check to make sure the stream is coming in UTF-8.

Cheers.
