### ISSUE TITLE
How to deal with "Map" structure?

### ISSUE THREAD

**Issue by lijixue** [json-iterator/java#45]
first, this is my test code:
```
public class Hero {
        private Map<**Integer**, Integer> foodNum;
	
	public Map<Integer, Integer> getFoodNum() {
		return foodNum;
	}
	
	public void setFoodNum(Map<Integer, Integer> foodNum) {
		this.foodNum = foodNum;
	}
}
```

```
public class Test {
        public static void main(String[] args) { 
                Hero hero = new Hero();
                Map<Integer, Integer> foodsNum = new HashMap<>();
                foodsNum.put(5, 99);
                hero.setFoodNum(foodsNum);
		
                String serialize = JsonStream.serialize(hero);
                System.out.println(serialize);

		JsonIterator.deserialize(serialize, Hero.class);
	}
}
```

I ran Test.main(), but I got an exception:ClassCastException: java.lang.Integer cannot be cast to java.lang.String. I searched some information, and found out that Map's key must be "String" in json-iterator, so that I changed Integer to String, I succeed in serialize, but I got an exception while deserializing:ArrayIndexOutOfBoundsException: 20. I can't comprehend it, and please help me.

there are my questions:
1. Is Map's key in json-iterator must be String? I have used "fastjson" before, and it and be Integer, although serialized string is not a right json string.
2. How can I deserialize an Object with Map strcture?

**Comment by taowen** [comment]
only map of string is supported. the key type must be string, as JSON map only support string key. There will be a extra mapping from string to other types. This can be done by a setter. Say you have a setFoodNum(Map<String, Integer> foodNum), then you can do the conversion from there

**Comment by lijixue** [comment]
thanks for your reply, but you didn't answer my 2nd question, I have changed my 'foodsNum' to Map<String, Integer> and setter, getter. and I changed my main function as follows:
```
public static void main(String[] args) {
	Hero hero = new Hero();
	Map<String, Integer> foodsNum = new HashMap<>();
	foodsNum.put("5", 99);
	hero.setFoodNum(foodsNum);
	String serialize = JsonStream.serialize(hero);
	System.out.println(serialize);
	JsonIterator.deserialize(serialize, Hero.class);
}
```
it output : {"foodNum":{"5":99}} and throws an exception : JsonException: java.lang.ArrayIndexOutOfBoundsException: 20.

I checked my code, and can't find where is the problem.

**Comment by taowen** [comment]
https://github.com/json-iterator/java/commit/602fca84b48bd9560e4d3b814cd18e18a7998319

It is a bug which affected the map of non string value type, in reflection mode. I will release a new version soon

**Comment by lijixue** [comment]
thanks a lot!
