### ISSUE TITLE
对象里有char类型反系列化报错

### ISSUE THREAD

**Issue by hao117** [json-iterator/java#47]
com.jsoniter.spi.JsonException: java.lang.IllegalArgumentException: argument type mismatch
	at com.jsoniter.ReflectionObjectDecoder$OnlyField.decode(ReflectionObjectDecoder.java:113)
	at com.jsoniter.JsonIterator.read(JsonIterator.java:336)
	at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:373)

**Comment by taowen** [comment]
给一下测试数据

**Comment by hao117** [comment]
{"flag":49,"text":"Tom is a cat!"}

public class Vo {
    private String text;
    private char flag;

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public char getFlag() {
        return flag;
    }

    public void setFlag(char flag) {
        this.flag = flag;
    }

}

**Comment by taowen** [comment]
https://github.com/json-iterator/java/commit/9fdbb09bc297d49813d4cac5ea79643c20f930fe

fixed, it is only a issue in reflection mode. You can set decoding mode to DecodingMode.DYNAMIC_MODE_AND_MATCH_FIELD_WITH_HASH
