### ISSUE TITLE
deserialize with byte[]

### ISSUE THREAD

**Issue by tokazio** [json-iterator/java#50]
Trying to deserialize a json file (getting byte[] with Files.readAllBytes).
I faced to this exception:
`com.jsoniter.spi.JsonException: deserialize: premature end`
Next I've tried with the string content directly like:

`
String str = "{\"port\":13110};
JsonIterator.deserialize(str, aClass);
`
Ok. But with the byte[] from this string:
`
String str = "{\"port\":13110};
JsonIterator.deserialize(str.getBytes(), aClass);
`
This gives:
`com.jsoniter.spi.JsonException: deserialize: premature end`

Then I'm giving new String() of the byte[] loaded from file as argument but don't understand why the byte[] as argument doesn't work directly.

**Comment by taowen** [comment]
can you give me the definition of aClass?

**Comment by taowen** [comment]
fixed

**Comment by tokazio** [comment]
fast! good! thanks, great work!
