### ISSUE TITLE
two-dimensional string array to JSON

### ISSUE THREAD

**Issue by GiantCrocodile** [json-iterator/java#54]
I tried to convert a two-dimensional string array to a JSON string. How can I do this? I tried to use JsonStream.serialize() with my string:

```java
String content = {
    {"key1", "value1"},
    {"key2", "value2"}
};
```

I want a JSON with both keys on same level - not as a JSON array. Jsoniter is just parsing the String and gives back an object with same structure as input - not JSON format. Please point me to the right direction or where I should look at the docs. I tried it for one hour and got no real use results.

**Comment by taowen** [comment]
can you give a sample code, with expected result?

**Comment by GiantCrocodile** [comment]
Hey @taowen! I want this JSON string to be crafted/produced by your JSON library without putting JSON formatting around the values and key names myself:

```java
"{\"type\": \"ANT_ACTION_GOLEFT\", \"color\": \"ANT_COLOR_BLUE\"}" 
```

**Comment by taowen** [comment]
```
"{\"type\": \"ANT_ACTION_GOLEFT\", \"color\": \"ANT_COLOR_BLUE\"}"
```

this is the input or output? If this is the output, what is the java code to define to object or map in the first place? Do you have a working piece of code?

**Comment by GiantCrocodile** [comment]
The quoted string is how it should look like (without the escape symbols of course). I want this output:

```json
{
"type": "ANT_ACTION_GOLEFT",
"color": "ANT_COLOR_BLUE"
}
```

but I don't know what kind of string or array object I should pass to serializer so I get this output.

**Comment by taowen** [comment]
```
HashMap<String, Object> map = new HashMap<String, Object>();
map.put("type", "ANT_ACTION_GOLEFT");
map.put("color", "ANT_COLOR_BLUE");
JsonStream.serialize(map);
```

**Comment by GiantCrocodile** [comment]
This works @taowen! Although it feels like it is a bit too complex for just two two keys with simple String values. Is there something where I can read up on which types are supported and how to put them into serializer, like to see if there are alternatives to HashMap for my case?

**Comment by taowen** [comment]
this is the simplest way...

**Comment by GiantCrocodile** [comment]
Okay, fair enough. Thank you :)! The docs were a bit hard to understand for me as a newbie to this lib.
