### ISSUE TITLE
Report classes covered and not covered by codegen

### ISSUE THREAD

**Issue by fabienrenaud** [json-iterator/java#59]
It is possible to run the static_code mode without having any (or all) classes generated. So it would be nice to generate a report at build time of nested/child types which do not have static code generated.

For example:

    class User {
       List<Tag> tags;
    }

If User.class is marked for codegen but not List<Tag>, the latter should be flagged. Either with a simple WARNING in the console (would be a nice first step) at build time or with some sort of report written to disk. This will make jsoniter much easier to productionize (where large teams may update the schema and forget to update the jsoniter codegen config without such checks).

**Comment by taowen** [comment]
I think the better behavior is to only mark `User` as to be codegen, then any dependencies can be discovered automatically. How about that?

**Comment by taowen** [comment]
just checked. In case User is added to codegen target, the referenced `List<Tag>` will be codegen automatically. It is already supported

**Comment by fabienrenaud** [comment]
Cool. May be mention this in the documentation?

**Comment by taowen** [comment]
Documentation updated
