### ISSUE TITLE
JsonIterator's read() looses precision when encounters a large long value

### ISSUE THREAD

**Issue by yurgisbaykshtis** [json-iterator/java#60]
Sometimes a value type is not known, so Object read() method is the only way to capture those. However for integer/long values it returns double even though there is no floating point. That leads to precision loss for large values:

```
JsonIterator` iter = JsonIterator.parse("{\"value\":1000000000000000001}");
iter.readObject();
long value = iter.readLong();
assertEquals(1000000000000000001L, value);
```

```
JsonIterator iter2 = JsonIterator.parse("{\"value\":1000000000000000001}");
iter2.readObject();
Object value2 = iter2.read();
assertEquals(1000000000000000001L, ((Number)value2).longValue());
```

The first assertion succeeds while the second fails. The read() method must be smarter and return a long in case where the floating point is not present in the value being read.

**Comment by taowen** [comment]
read() will always return Double for any kind of number, I believe this is the common behavior for all json libraries. It is a feature not a bug.

**Comment by yurgisbaykshtis** [comment]
That is strange, it literally means (for json as a transfer protocol) bits in != bits out.
Is there any workaround in jsoniter to get actually what is there without knowing a type a priori?

**Comment by yurgisbaykshtis** [comment]
Also Jackson does not seem to offer an analog of the Object read() method, instead it provides a token value type (in this case it would be JsonToken.VALUE_NUMBER_FLOAT  or JsonToken.VALUE_NUMBER_INT), which can be used to decide whether to extract the value as double or long without loss of precision.

**Comment by taowen** [comment]
you can use readAny and try convert to long or float

**Comment by taowen** [comment]
consolidate into https://github.com/json-iterator/java/issues/149
