### ISSUE TITLE
read(Number.class) support int/float/long/BigDecimal

### ISSUE THREAD

**Issue by taowen** [json-iterator/java#61]

**Comment by kulshreshtha19** [comment]
please provide description of this issue

**Comment by taowen** [comment]
read will always use double as return value currently, by supporting read(Number.class) to return a Number instead. it might be int/floag/long/BigDecimal depending the input (having decimal or not, or how long)

**Comment by taowen** [comment]
consolidate into https://github.com/json-iterator/java/issues/149
