### ISSUE TITLE
json-iterator not compatible with JDK 9

### ISSUE THREAD

**Issue by topkool** [json-iterator/java#67]
We are facing with a bug on some windows machines preventing us to use JDK 8 (for development purpose only). It seems to be due to a windows library (msvcrXXX.dll), and the bug has been raised to Oracle.

Anyway, the only solution for now was to use JDK9, but json-iterator does not work:

> Exception in thread "main" com.jsoniter.spi.JsonException: failed to generate encoder for: java.util.Map<java.lang.String, com.jsoniter.any.Any> with [class java.lang.String, class com.jsoniter.any.Any], exception: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @7c417213
> public static void encode_(java.lang.Object obj, com.jsoniter.output.JsonStream stream) throws java.io.IOException
> 

Any clue?

**Comment by taowen** [comment]
can you provide a full example? Can you open java.lang module using `java --add-opens java.base/java.lang=ALL-UNNAMED`

**Comment by topkool** [comment]
I run 2 simple tests: 

```
public static void main(String[] args) throws UnsupportedEncodingException, IOException {
    String jsonStr = new String(Files.readAllBytes(Paths.get("D:\\SRC\\test_json\\src\\test.json")), StandardCharsets.UTF_8);

    JsonIterator jsonIter = new JsonIterator();
    jsonIter.reset(jsonStr.getBytes("UTF-8"));

    // Test n°1 (with Any) => It works
    Any json = jsonIter.read(Any.class);
    String ret = JsonStream.serialize(json);
    System.out.printf("[%s]\n", ret);

    // Test n°2 (with class binding) => It does'nt work
    TestMapping test = jsonIter.read(TestMapping.class);
    ret = JsonStream.serialize(test);
    System.out.printf("[%s]\n", ret);
}
```

Hereafter is the TestMapping class:
```
public class TestMapping {    
	private int version;
	private String data;
}
```

Hereafter is the json:
```
{
   "version" : 123,
   "data" : "99887766554433221187qsdqsdqsdqsdqsdqsddqsd"
}
```

Results:
- The 1st test works (with Any)
- The 2nd test fails (with class binding) with the following error (after adding the JVM option --add-opens java.base/java.lang=ALL-UNNAMED):

> 
> Exception in thread "main" com.jsoniter.spi.JsonException: java.lang.ArrayIndexOutOfBoundsException: 85
> 	at com.jsoniter.ReflectionObjectDecoder$OnlyField.decode(ReflectionObjectDecoder.java:116)
> 	at com.jsoniter.JsonIterator.read(JsonIterator.java:345)
> 	at CryptoTest_AESNI.main(CryptoTest_AESNI.java:206)
> Caused by: java.lang.ArrayIndexOutOfBoundsException: 85
> 	at com.jsoniter.IterImpl.nextToken(IterImpl.java:154)
> 	at com.jsoniter.JsonIterator.readNull(JsonIterator.java:147)
> 	at com.jsoniter.ReflectionObjectDecoder$OnlyField.decode_(ReflectionObjectDecoder.java:121)
> 	at com.jsoniter.ReflectionObjectDecoder$OnlyField.decode(ReflectionObjectDecoder.java:114)
> 	... 2 more

**Comment by taowen** [comment]
I can not reproduce the issue with linux + amd64 + jdk9. However, I notice the array out bound at position 85. The input json is only 80 character. Are you adding unprintable char in the file? Can you give me the original test file?

Also, which version of jsoniter are you using? I do not need `java --add-opens java.base/java.lang=ALL-UNNAMED` with latest version of jsoniter in reflection mode.

**Comment by topkool** [comment]
Strange, I cannot see any unprintable characters (using Notepad+) except CR/LF at the end of each line.

Please find the original file in attachment.

[test.zip](https://github.com/json-iterator/java/files/1053970/test.zip)

**Comment by taowen** [comment]
It is caused by

```
Any json = jsonIter.read(Any.class);
    String ret = JsonStream.serialize(json);
    System.out.printf("[%s]\n", ret);
```

jsonIter is stateful. At this point, it has already reached the end of file. so reading more input will casue exception. The error might be not helpful.

**Comment by topkool** [comment]
But what's wrong with that piece of code? What should I do (or should not do)?

**Comment by taowen** [comment]
you need to create new instance of JsonIter, or reset it, before parse the same input again
