### ISSUE TITLE
about toolchains

### ISSUE THREAD

**Issue by kimmking** [json-iterator/java#69]
it's nice job.
if we can make some tools connecting other project like springmvc,springboot,jaxrs, swagger,camel-dataformat and so on,it should be widely used.

**Comment by kimmking** [comment]
And why use codegen to process json ( fastjson use ASM here )? 
PS: I feel the codes of this project a little DSL/Script style.

**Comment by taowen** [comment]
contribution is welcomed~

ASM is not enough to optimize the runtime code. full codegen gives the hotspot better chance to optimize the code.
