### ISSUE TITLE
对泛型类的转换有点问题

### ISSUE THREAD

**Issue by qiaokang** [json-iterator/java#7]
java.lang.RuntimeException: unsupported type: T

**Comment by taowen** [comment]
给一段完整的复现问题的源代码

**Comment by qiaokang** [comment]
[jsonBean.zip](https://github.com/json-iterator/java/files/659912/jsonBean.zip)
将context.json转换为ProductAdvertList对象的时候,报异常java.lang.RuntimeException: unsupported type: T

**Comment by taowen** [comment]
@qiaokang 现在已经ok了，你再试试看

**Comment by qiaokang** [comment]
谢谢@taowen ,顺利解析。
我发现json的值类型与bean的属性类型必须强一致，例如值类型是数字，对应bean的属性类型如果是String,会报解析异常，类型不匹配。
意外的惊喜，原来一直使用GSON，类型没有匹配。
