### ISSUE TITLE
support equals() and hashCode()

### ISSUE THREAD

**Issue by gganssauge** [json-iterator/java#72]
It would be very useful to have equals() and hashCode() available.
Would at least make my life much easier.

**Comment by gganssauge** [comment]
Sorry - was a bit too fast.
I'm speaking of the Any class and it's subclasses.
I have a scenario where I would like to use these like Object instances.

**Comment by taowen** [comment]
@gganssauge It is supported now, please give it a try: https://oss.sonatype.org/content/repositories/snapshots/com/jsoniter/jsoniter/0.9.14-SNAPSHOT/
