### ISSUE TITLE
read large number as object

### ISSUE THREAD

**Issue by taowen** [json-iterator/java#74]
when value is too large, what will happen?

**Comment by caoli5288** [comment]
Jsoniter can handle number greater than Long.MAX_VALUE both in lazy API but can't cast it to primitive value. 
```
        String val = "[" + Long.MAX_VALUE + "555" +
                "]";// 9223372036854775807555
        Iterator<Any> itr = JsonIterator.deserialize(val).iterator();
        Any any = itr.next();
        System.out.println(any);// 9223372036854775807555
        any.toLong();// then thr exception
        any.object();// also will thr exception, jsoniter 
```
new API Any.toBigInteger() and Any.toBigDecimal() may needed.

**Comment by caoli5288** [comment]
And not very good in another API. Will cause incorrect value. 
```
        String val = "[" + Long.MAX_VALUE + "555" +
                "]";
        JsonIterator itr = JsonIterator.parse(val);
        try {
            itr.readArray();
            System.out.println(itr.read());// it output 9.223372036854776E21, same to 9223372036854776000
        } catch (IOException e) {
        }
```

**Comment by taowen** [comment]
toLong() should throw exception. If not, you can give me a pull request.

iter.read() will return double, this is same as jackson or gson. We can add a global config to return BigDecimal for number when type is Object.class. Like golang UserNumber().

toBigDecimal is not necessary, `as(BigDecimal.class)`

**Comment by taowen** [comment]
consolidate into https://github.com/json-iterator/java/issues/149
