### ISSUE TITLE
com.jsoniter.spi.EmptyEncoder used by static code gen - class doesn't exist

### ISSUE THREAD

**Issue by oliverdrake** [json-iterator/java#75]
When using static code gen I ended up with a generated class that extends com.jsoniter.spi.EmptyEncoder which doesn't appear to exist (anymore?)

**Comment by taowen** [comment]
should be fixed now

https://oss.sonatype.org/content/repositories/snapshots/com/jsoniter/jsoniter/0.9.14-SNAPSHOT/

**Comment by oliverdrake** [comment]
Brilliant, thanks for the fast response, I'll try it out tomorrow
