### ISSUE TITLE
readDouble/readFloat parsing issue

### ISSUE THREAD

**Issue by lquerel** [json-iterator/java#76]
readDouble doesn't like the combination of dot and exponent.

JsonIterator.parse("8.37377E9").readDouble() returns 8.37377 instead of 8373770000

**Comment by lquerel** [comment]
version 0.9.13

**Comment by taowen** [comment]
should be fixed now

https://oss.sonatype.org/content/repositories/snapshots/com/jsoniter/jsoniter/0.9.14-SNAPSHOT/

**Comment by lquerel** [comment]
Works. Thanks for this quick fix.
