### ISSUE TITLE
Simply ignore default value in serialize

### ISSUE THREAD

**Issue by caoli5288** [json-iterator/java#77]
Hi. I had to write a TypeAdapter in Gson. Hope you can provide a simpler way I can more easily mig some project from gson to jsoniter. :-). Like below
```Java
class Foo {
  int bar = 1;
} 

@Test
void main() {
  Foo foo = new Foo();
  Assert.assertTrue(JsonStream.serialize(foo).equals("{\"foo\":1}"));
  // Then set JsonStream ignore object's default value
  // ....
  Assert.assertTrue(JsonStream.serialize(foo).equals("{}"));
}
```
THX for your great project!

**Comment by taowen** [comment]
Gson will not ignore `int bar = 1;`, it requires you to write a `TypeAdater`.

In jsoniter, you can `registerTypeEncoder`.

**Comment by caoli5288** [comment]
@taowen So what? wait...我还是说中文好了，，

哥，我第一句话说的就是Gson里得自己写个TypeAdapter，希望这个项目能提供个simpler的办法，所以你不用再告诉我一遍，Gson不会忽略int bar = 1的，

然后我也没问这个项目里，什么相当于Gson的TypeAdapter来着，，，很尴尬啊，

**Comment by taowen** [comment]
如果有simple的办法，肯定大家都会搞。问题就是在java里没有简单的办法去拿到这个默认值。除非创建一个新的实例。但是很多java对象是不能随便创建的，比如构造函数可能是私有的，或者构造函数有副作用。最简单的办法也是给你一个默认值的annotation，还是需要再填一遍。

**Comment by caoli5288** [comment]
@taowen 那能不能提供一个选项，忽略原始数字类型的0值呢

**Comment by taowen** [comment]
现在的行为和gson一样，只忽略null的值。也不打算支持更多的忽略类型。

**Comment by caoli5288** [comment]
好的，谢谢回复

**Comment by caoli5288** [comment]
扫了一遍你的代码，你的实现是在Bind里，单独给每一个属性设置shouldOmitNull，实际项目里面很少会出现一个对象里，某个属性忽略null，某个属性不忽略null吧？

在Config里定义成全局的是不是合理一些，

**Comment by caoli5288** [comment]
#80 开了个pull，自己稍微跑了下测试没问题，

我在stackoverflow上看到有人问Gson怎么样忽略为0的field，https://stackoverflow.com/questions/25804952/how-to-config-gson-to-exclude-0-integer-values，
感觉这是个很普遍需求来着？应该除了我还是有人需要的，

还是希望可以合并，自己维护个分支很麻烦，
