### ISSUE TITLE
Dynamic mode issue in none public class

### ISSUE THREAD

**Issue by caoli5288** [json-iterator/java#79]
![qq 20170624020746](https://user-images.githubusercontent.com/3120587/27494802-058a9abc-5882-11e7-89d0-e487ac826869.png)

It output an empty json object without any info or exception. I think it should thr a exception in this case. :-(

**Comment by caoli5288** [comment]
暂时发现ASM生成的代码在以下情况下跟默认的反射行为不一致，
* class 非public
* field 非public并且没有对应的getter

如果行为不一致的话最好还是在README里说明下，

**Comment by caoli5288** [comment]
都了下动态代码生成部分的代码，暂时没完全理清楚`CodegenResult`那包装好几层的代码生成方式，绕来绕去的，`buffer()`这个方法好像完全可以直接包装成`append("stream.writeRaw(" + (.*) + ")")`来的？中间放list暂存了一道真的让第一次读代码的人难以看明白逻辑，

生成的代码好像也有小问题，这样一个类，——
```Java
    public static class Foo {

        public float bar;
        public float bar1;
    }
```

生成的代码是这样的，——
```Java
public static void encode_(com.jsoniter.Main.Foo obj, com.jsoniter.output.JsonStream stream) throws java.io.IOException {
stream.writeVal((float)obj.bar1);
stream.writeRaw(",\"bar\":", 7);
stream.writeVal((float)obj.bar);
}

public void encode(Object obj, com.jsoniter.output.JsonStream stream) throws java.io.IOException {
if (obj == null) { stream.writeNull(); return; }
stream.writeRaw("{\"bar1\":", 8);
encode_((com.jsoniter.Main.Foo)obj, stream);
stream.write((byte)'}');
}
```

第一个key，是在`encode()`里面写的，然后第一个value，和之后的k/v都是在encode_里面写的，这样做有什么好处？根本没必要的吧。。。

**Comment by taowen** [comment]
两个行为不一致符合预期，因为codegen无法访问private的类或者成员。这个我改一下文档。

拆分成两个encode是因为性能，减少调用writeRaw的次数。

**Comment by caoli5288** [comment]
我建议如果连class都不是public的话，直接抛异常比较直观，

**Comment by taowen** [comment]
done
