### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by biezhi** [json-iterator/java#9]
1. 源代码中加点注释
2. 可以在`readme`中展示常用的功能，如对象转JSON，直接获取基本数据类型

**Comment by taowen** [comment]
嗯，很好的建议。我改一下。对象转回到JSON，这个还在开发。直接获取基本数据类型是指什么呢？

**Comment by biezhi** [comment]
比如
```java
String name = json.getString("name");
int age = json.getInt("age");
```

**Comment by taowen** [comment]
`jsoniter.readAny().toString("name")` 返回的any对象可以访问深层嵌套的值，比如toInt("field1", "nextLevelField2", 5, "nextNextLevelField3")类似这样的。toInt等函数会尽最大的可能把类型转换为你想要的，类似javascript的弱类型转换。
