### ISSUE TITLE
中文转换乱码

### ISSUE THREAD

**Issue by bjcawanglu** [json-iterator/java#90]
用JsonIterator.parse(json)转换 对象，如json 包含中文，转出的对象出现乱码情况，看了文档没有找到解决方法，希望可以得到你的帮助，谢谢。

**Comment by taowen** [comment]
给一段测试的json文本

**Comment by caoli5288** [comment]
@bjcawanglu json是从文件或网络读的吗，编码是什么

**Comment by bjcawanglu** [comment]
提供的服务是UTF-8，服务器的编码是GB2312，json-iterator转对象是否依据服务器的默认编码？
我的JSON是在request.getattribute里面获取的，在本地Windows 上 debug 不显示乱码，在服务器上显示乱码导致异常，现在已经更换了转换JSON的工具。

**Comment by taowen** [comment]
只支持utf8
