### ISSUE TITLE
Problems with serialization

### ISSUE THREAD

**Issue by ukchucktown** [json-iterator/java#91]
I have the following code:

public abstract class TokenFactory {
    @JsonProperty(to={"client_id"})
    private String clientId;

    @JsonProperty(to={"client_secret"})
    private String clientSecret;

    @JsonProperty(to={"grant_type"})
    private String grantType;

    public TokenFactory(String clientId, String clientSecret) {
        this(clientId, clientSecret, "client_credentials");
    }

    public TokenFactory(String clientId, String clientSecret, String grantType) {
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.grantType = grantType;
    }

    public String getClientId() {
        return clientId;
    }

    public String getClientSecret() {
        return clientSecret;
    }

    public String getGrantType() {
        return grantType;
    }

    public abstract Token getToken(String url);
}

When I try to serialize it I get the following output:
{"client_id":"...","client_secret":"...","grant_type":"client_credentials","clientId":"...","clientSecret":"...","grantType":"client_credentials"}

That's obviously not what I want but there is not much documentation on serialization. What do I need to do to get client_id, client_secret and grant_type as the JSON properties w/o the duplicate clientId, clientSecret and grantType.

Thanks,
Grant

**Comment by taowen** [comment]
You need to mark @JsonProperty on the getters instead

**Comment by ukchucktown** [comment]
Yeah, I did and it still generates the duplicate property values. The only way it works is to mark all the private fields with @JsonIgnore. Is this a bug or expected behavior?

 

package mil.navy.spawar.m2r2.data.itc;

import com.jsoniter.annotation.JsonProperty;

public abstract class TokenFactory {
    private String clientId;
    private String clientSecret;
    private String grantType;

    public TokenFactory(String clientId, String clientSecret) {
        this(clientId, clientSecret, "client_credentials");
    }

    public TokenFactory(String clientId, String clientSecret, String grantType) {
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.grantType = grantType;
    }

    @JsonProperty(to={"client_id"})
    public String getClientId() {
        return clientId;
    }

    @JsonProperty(to={"client_secret"})
    public String getClientSecret() {
        return clientSecret;
    }

    @JsonProperty(to={"grant_type"})
    public String getGrantType() {
        return grantType;
    }

    public abstract Token getToken(String url);
}

**Comment by ukchucktown** [comment]
The subclass that actually calls serialize…

 

public class PhoenixTokenFactory extends TokenFactory {
    public PhoenixTokenFactory(String clientId, String clientSecret) {
        super(clientId, clientSecret);
    }

    public Token getToken(String url) {
        Client client = new RestClient().getClient();

        // create the form
        Form form = new Form();
        form.param("data", JsonStream.serialize(this));

        // do post
        WebTarget webTarget = client.target(url);
        String jsonResult = webTarget
                .request()
                .post(Entity.form(form), String.class);

        // return token
        return JsonIterator.deserialize(jsonResult, Token.class);
    }
}

**Comment by taowen** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/jsoniter/jsoniter/0.9.16-SNAPSHOT/

It is bug, should be fixed
