### ISSUE TITLE
Serialisation of strings with bytes

### ISSUE THREAD

**Issue by expobrain** [json-iterator/java#93]
Serialising strings with arbitrary bytes generates an invalid JSON representation. For instance:
 
`JsonStream.serialize(new String(new byte[]{0x00}))`

should return `"\u0000"` as per specs (see http://json.org/string.gif at http://json.org/).

**Comment by taowen** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/jsoniter/jsoniter/0.9.16-SNAPSHOT/

should be fixed
