### ISSUE TITLE
Custom field names are ignored when serializing

### ISSUE THREAD

**Issue by kabochkov** [json-iterator/java#97]
I expect the following class to serialize for ex. in `{"model_name":"Audi"}`, but `@JsonProperty` value is ignored and I get  `{"modelName":"Audi"}`

```
    public static class Car {

        private String modelName;

        public Car(@JsonProperty("model_name") String carName) {
            this.modelName = carName;
        }

        @JsonProperty("model_name")
        public String getModelName() {
            return modelName;
        }
    }
```

**Comment by taowen** [comment]
@JsonProperty on constructor is not supported

**Comment by AnarSultanov** [comment]
@taowen 
For me it does not work even on fields. When I try to deserialize 

> "{"first_name": "Name", "last_name": "Lastname", "birth_date": 177340800, "gender": "m", "id": 1, "email": "email@mail.ru"}"

to
```
public class User {
    private Integer id;
    private String email;
    @JsonProperty("first_name")
    private String firstName;
    @JsonProperty("last_name")
    private String lastName;
    private Character gender;
    @JsonProperty("birth_date")
    private Long birthDate;
```
I'm getting :

> "User{id=1, email='email@mail.ru', firstName='null', lastName='null', gender=m, birthDate=null}"

**Comment by taowen** [comment]
getter will override private field. try mark @JsonProperty on getter instead

**Comment by AnarSultanov** [comment]
I tried, didn't help. So I had to create custom decoder and encoder for my object.

**Comment by taowen** [comment]
refer to https://github.com/json-iterator/java/commit/732312ffeb1b9525ea9fcb7d185039dbada9fef7 , the @JsonProperty should be added to setter for deserialization.
